# Generated by Django 3.1.3 on 2022-05-30 11:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.PositiveBigIntegerField()),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.DateField(default=datetime.datetime.today)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('breakfast', models.TimeField()),
                ('lunch', models.TimeField()),
                ('dinner', models.TimeField()),
                ('blood_grp', models.CharField(max_length=10)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trackweight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('before_food', models.BooleanField(default=True)),
                ('after_food', models.BooleanField(default=False)),
                ('time_slot', models.PositiveSmallIntegerField(default=1)),
                ('intake_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.profile')),
            ],
        ),
    ]
