# Generated by Django 4.0.4 on 2022-06-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_symptoms_usersymptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_id', models.CharField(max_length=12)),
                ('checkup_date', models.DateTimeField()),
                ('checkup_type', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveBigIntegerField()),
                ('specialization', models.CharField(max_length=20)),
                ('doctor_id', models.CharField(max_length=12)),
                ('works_in', models.CharField(max_length=12)),
                ('sex', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=12)),
                ('generated_on', models.DateTimeField()),
                ('generates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='health.checkup')),
            ],
        ),
        migrations.CreateModel(
            name='Mental_health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=12)),
                ('suggestion', models.CharField(max_length=12)),
                ('score', models.CharField(max_length=12)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Disease_prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_id', models.CharField(max_length=12)),
                ('predictor_type', models.CharField(max_length=12)),
                ('is_verified', models.CharField(max_length=12)),
                ('scan_path', models.CharField(max_length=12)),
                ('prediction', models.CharField(max_length=12)),
                ('name_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.profile')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='checkup',
            name='checkup_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.profile'),
        ),
    ]
