# Generated by Django 3.1.3 on 2022-06-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_checkup_doctor_alter_profile_username_report_and_more'),
        ('health', '0004_symptoms_usersymptoms'),
    ]

    operations = [
    ]
