# Generated by Django 3.1.3 on 2022-07-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_merge_20220620_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='breakfast',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dinner',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lunch',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(),
        ),
    ]
