# Generated by Django 3.1.3 on 2022-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20220704_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sex',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='works_in',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_grp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
